services:
  - type: web
    name: jade-car-simulation
    env: docker
    dockerfilePath: ./Dockerfile.release
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 6080